// Generated by CoffeeScript 1.12.2

/*
 * Global varible for encoding to littleEndian
 */

(function() {
  var isLittleEndian, littleEndian, toBytes, toBytesBigEndian, toBytesLittleEndian, toNumBigEndian, toNumLittleEndian, toNumber;

  littleEndian = true;


  /*
   * Update encoding/decoding convertion
   * @param value
   */

  isLittleEndian = function(value) {
    return littleEndian = value ? true : false;
  };


  /*
   * Convert number to bytes array
   * @param num
   * @param syze (array)
   * @return array
   * @exception Illegal syze
   */

  toBytes = function(num, syze) {
    if (littleEndian) {
      return toBytesLittleEndian(num, syze);
    } else {
      return toBytesBigEndian(num, syze);
    }
  };


  /*
   * Convert bytes array to number
   * @param bytes array
   * @return number
   */

  toNumber = function(bytes) {
    if (littleEndian) {
      return toNumLittleEndian(bytes);
    } else {
      return toNumBigEndian(bytes);
    }
  };


  /*
   * Convert number to bytes array (encoding to littleEndian)
   * @param num
   * @param syze (array)
   * @return array
   * @exception Illegal syze
   */

  toBytesLittleEndian = function(num, syze) {
    var bytes, i, j;
    bytes = [];
    i = syze && typeof syze === 'number' ? syze : 8;
    j = i - 1;
    while (true) {
      bytes[j - (--i)] = num & 255;
      num = num >> 8;
      if (!i) {
        break;
      }
    }
    if (num !== 0) {
      throw new Error("Illegal syze.");
    }
    return bytes;
  };


  /*
   * Convert number to bytes array (encoding to bigEndian)
   * @param num
   * @param syze (array)
   * @return array
   * @exception Illegal syze
   */

  toBytesBigEndian = function(num, syze) {
    var bytes, i;
    bytes = [];
    i = syze && typeof syze === 'number' ? syze : 8;
    while (true) {
      bytes[--i] = num & 255;
      num = num >> 8;
      if (!i) {
        break;
      }
    }
    if (num !== 0) {
      throw new Error("Illegal syze.");
    }
    return bytes;
  };


  /*
   * Convert bytes array to number (decoding to littleEndian)
   * @param bytes array
   * @return number
   * @exception undefined exception, null exception
   */

  toNumLittleEndian = function(bytes) {
    var i, val;
    val = 0;
    if (typeof bytes === 'undefined' || bytes === null) {
      throw new Error("UndefinedOrNullValue");
    }
    i = bytes.length - 1;
    if (!(Array.isArray(bytes)) || i < 0) {
      return 0/0;
    }
    while (true) {
      val += bytes[i];
      if (i > 0) {
        val = val << 8;
      }
      if (i === 0) {
        break;
      }
      --i;
    }
    if (val && typeof JSON.parse(JSON.stringify(val)) === 'number') {
      return val;
    } else {
      return 0/0;
    }
  };


  /*
   * Convert bytes array to number (decoding to bigEndian)
   * @param bytes array
   * @return number
   */

  toNumBigEndian = function(bytes) {
    var byte, i, k, len, val;
    val = 0;
    if (typeof bytes === 'undefined' || bytes === null) {
      throw new Error("UndefinedOrNullValue");
    }
    if (!(Array.isArray(bytes)) || bytes.length === 0) {
      return 0/0;
    }
    for (i = k = 0, len = bytes.length; k < len; i = ++k) {
      byte = bytes[i];
      val += byte;
      if (i > bytes.length - 1) {
        val = val << 8;
      }
    }
    if (val && typeof JSON.parse(JSON.stringify(val)) === 'number') {
      return val;
    } else {
      return 0/0;
    }
  };

  module.exports.isLittleEndian = isLittleEndian;

  module.exports.toBytes = toBytes;

  module.exports.toNumber = toNumber;

}).call(this);
